create database staging;

use staging;

create table staging (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cod VARCHAR(10),
    message VARCHAR(100),
    cnt VARCHAR(100),
    city_id VARCHAR(100),
    city_name VARCHAR(100),
    city_latitude VARCHAR(100),
    city_longitude VARCHAR(100),
    city_country_code VARCHAR(10),
    city_population VARCHAR(100),
    city_timezone VARCHAR(100),
    city_sunrise VARCHAR(100),
    city_sunset VARCHAR(100),
    dt VARCHAR(100),
    dt_txt VARCHAR(100),
    main_temp VARCHAR(100),
    main_feels_like VARCHAR(100),
    main_temp_min VARCHAR(100),
    main_temp_max VARCHAR(100),
    main_pressure VARCHAR(100),
    main_sea_level VARCHAR(100),
    main_grnd_level VARCHAR(100),
    main_humidity VARCHAR(100),
    main_temp_kf VARCHAR(100),
    weather_id VARCHAR(100),
    weather_main VARCHAR(50),
    weather_description VARCHAR(100),
    weather_icon VARCHAR(50),
    clouds_all VARCHAR(100),
    wind_speed VARCHAR(100),
    wind_deg VARCHAR(100),
    wind_gust VARCHAR(100),
    visibility VARCHAR(100),
    pop VARCHAR(100),
    rain_3h VARCHAR(100),
    sys_pod VARCHAR(5),
    timeGet VARCHAR(100)
);